# Generated by Django 5.2.5 on 2025-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_artistprofile_avatar_alter_artistprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_avatars/'),
        ),
    ]
