# Generated by Django 5.2.5 on 2025-11-25 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_artistprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
