# Generated by Django 5.2.5 on 2025-08-30 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('remaining', models.PositiveIntegerField(default=3)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download', to='orders.orderitem')),
            ],
        ),
    ]
