# Generated by Django 5.2.5 on 2026-01-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
